version: '3'
services:
  ant_lib:
    command: ["npm", "run", "build-and-test-debug"]
    environment:
      NODE_DEBUG_PORT_INNER: ${NODE_DEBUG_PORT_INNER}
    depends_on:
      - ant_redis
    ports:
      - "${NODE_DEBUG_PORT_OUTER}:${NODE_DEBUG_PORT_INNER}"
