version: '3'
services:
  ant_lib:
    command: ["npm", "run", "build-and-test-debug"]
    environment:
      NODE_DEBUG_PORT_INNER: ${NODE_DEBUG_PORT_INNER}
    ports:
      - "${NODE_DEBUG_PORT_OUTER}:${NODE_DEBUG_PORT_INNER}"
  ant_redis:
    ports:
      - "${REDIS_DEBUG_PORT_OUTER}:6379"
