version: '3'
services:
  ant_lib:
    build: .
    volumes:
      - .:/app
    depends_on:
      - ant_redis
    stdin_open: true
    networks:
      - ant
  ant_redis:
    image: redis:5.0.3-alpine
    networks:
      - ant
networks:
  ant:
    driver: bridge
