version: '3'
services:
  ant_lib:
    command: ["npm", "run", "ci"]
    environment:
      COVERALLS_GIT_BRANCH: ${GITHUB_BRANCH}
      COVERALLS_GIT_COMMIT: ${GITHUB_SHA}
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
